PROJECT = "@DOXYGEN_PROJECT_NAME@"
VERSION = "@DOXYGEN_PROJECT_VERSION@"

# m.css / Doxygen config
DOXYGEN_OUTPUT = "@DOXYGEN_OUTPUT_DIRECTORY@"
SEARCH = True
FINE_BRANCHES = True
M_OUTPUT = "@DOXYGEN_OUTPUT_DIRECTORY@/html"
